"""End-to-end incident clustering, deduplication, and indexing pipeline orchestrator."""
import uuid
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional, Set
from collections import defaultdict, deque

from backend.core.config import settings
from backend.core.logging import get_logger
from backend.db.session import async_session_factory
from backend.models.incident import Incident, IncidentCandidate
from backend.db.repositories.incident_repo import IncidentRepository
from backend.clustering.candidate import IncidentCandidateData, deduplicate_log_batch
from backend.clustering.redis_index import redis_index, RedisFingerprintIndex
from backend.clustering.vector_index import vector_index, QdrantVectorIndex
from backend.clustering.clusterer import incident_clusterer, HDBSCANIncidentClusterer
from backend.clustering.embeddings.factory import get_embedding_provider
from backend.clustering.embeddings.base import BaseEmbeddingProvider

logger = get_logger(__name__)


class IncidentClusteringPipeline:
    """Coordinates batch log ingestion, normalization, Redis deduplication,

    trace co-occurrence graph correlation, Qdrant similarity search,
    HDBSCAN clustering, and PostgreSQL persistence.
    """

    def __init__(
        self,
        embedding_provider: Optional[BaseEmbeddingProvider] = None,
        redis_idx: Optional[RedisFingerprintIndex] = None,
        vector_idx: Optional[QdrantVectorIndex] = None,
        clusterer: Optional[HDBSCANIncidentClusterer] = None,
    ):
        self.embedding_provider = embedding_provider or get_embedding_provider()
        self.redis_index = redis_idx or redis_index
        self.vector_index = vector_idx or vector_index
        self.clusterer = clusterer or incident_clusterer

    def _determine_severity(self, candidates: List[IncidentCandidateData]) -> str:
        """Derive incident severity from constituent candidates."""
        for c in candidates:
            log = c.representative_log or {}
            lvl = str(log.get("level", "") or log.get("log_level", "")).upper()
            if lvl == "CRITICAL":
                return "CRITICAL"
            err = (c.error_code or "").upper()
            if "CRITICAL" in err or "TIMEOUT" in err or "EXHAUSTION" in err:
                return "HIGH"
        return "MEDIUM"

    def _resolve_root_candidate(
        self,
        candidates: List[IncidentCandidateData],
    ) -> IncidentCandidateData:
        """Resolve the root cause candidate in a multi-service cascade group.

        Prioritizes:
        1. Explicit unhandled exceptions (origin of stack trace)
        2. Innermost downstream services (not making downstream calls)
        3. Earliest timestamp
        Completely domain-agnostic without hardcoded service topologies.
        """
        def candidate_priority_score(c: IncidentCandidateData) -> tuple:
            log = c.representative_log or {}
            has_exception = 1 if (c.event_type == "unhandled_exception" or log.get("exception")) else 0
            # A service that did NOT call a downstream service is deeper in the call graph
            is_terminal = 1 if not log.get("downstream_service") else 0
            # Higher score = more likely the root cause
            return (has_exception, is_terminal, -c.first_seen.timestamp())

        sorted_candidates = sorted(candidates, key=candidate_priority_score, reverse=True)
        return sorted_candidates[0]

    def _build_incident_title(
        self,
        primary_service: str,
        candidates: List[IncidentCandidateData],
    ) -> str:
        """Generate a concise, informative, expressive incident title for AI reasoning."""
        root_cand = self._resolve_root_candidate(candidates)
        err = root_cand.error_code or root_cand.event_type or "Error"
        short_desc = root_cand.normalized_text[:80] if root_cand.normalized_text else "Failure event"
        return f"[{primary_service.upper()}] {err}: {short_desc}"

    def _extract_trace_connected_components(
        self,
        candidates: List[IncidentCandidateData],
    ) -> List[List[IncidentCandidateData]]:
        """Group candidates into connected components based on shared distributed trace IDs.

        Builds an undirected co-occurrence graph between candidates where an edge
        indicates they were generated by the same distributed user transaction.
        Domain-agnostic and topological-agnostic.
        """
        n = len(candidates)
        if n <= 1:
            return [[c] for c in candidates]

        adj: Dict[int, List[int]] = defaultdict(list)
        for i in range(n):
            for j in range(i + 1, n):
                if candidates[i].has_trace_overlap(candidates[j]):
                    adj[i].append(j)
                    adj[j].append(i)

        visited: Set[int] = set()
        components: List[List[IncidentCandidateData]] = []

        for i in range(n):
            if i not in visited:
                comp_indices: List[int] = []
                queue = deque([i])
                visited.add(i)
                while queue:
                    curr = queue.popleft()
                    comp_indices.append(curr)
                    for neighbor in adj[curr]:
                        if neighbor not in visited:
                            visited.add(neighbor)
                            queue.append(neighbor)
                components.append([candidates[idx] for idx in comp_indices])

        return components

    async def process_batch(self, raw_logs: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Execute the full Stage 2 streaming clustering pipeline on a log batch.

        Args:
            raw_logs: Raw log dictionaries received from Kafka consumer.

        Returns:
            Processing summary statistics dictionary.
        """
        start_time = datetime.now(timezone.utc)
        stats = {
            "total_raw_logs": len(raw_logs),
            "filtered_logs": 0,
            "deduplicated_candidates": 0,
            "redis_fingerprint_hits": 0,
            "qdrant_semantic_matches": 0,
            "new_incidents_created": 0,
            "new_candidates_created": 0,
            "status": "success",
        }

        if not raw_logs:
            return stats

        # 1. Filter ERROR and WARNING logs
        monitored_levels = settings.monitored_log_levels_set
        actionable_logs = [
            log for log in raw_logs
            if isinstance(log, dict) and str(log.get("log_level") or log.get("level") or "").upper() in monitored_levels
        ]

        # Fold out generic HTTP response wrappers if genuine application errors exist for that trace
        traces_with_app_errors = {
            str(log.get("trace_id") or (log.get("context") or {}).get("trace_id"))
            for log in actionable_logs
            if log.get("event_type") not in ("http_response_error", "http_response_warning", "http_access")
            and (log.get("trace_id") or (log.get("context") or {}).get("trace_id"))
        }

        pruned_logs = []
        for log in actionable_logs:
            evt = log.get("event_type")
            tid = str(log.get("trace_id") or (log.get("context") or {}).get("trace_id"))
            if evt in ("http_response_error", "http_response_warning", "http_access") and tid in traces_with_app_errors:
                # Omit duplicate transport wrapper in favor of application exception
                continue
            pruned_logs.append(log)

        stats["filtered_logs"] = len(pruned_logs)
        if not pruned_logs:
            logger.info("Batch contained 0 actionable logs after pruning. Skipping.")
            return stats

        # 2. In-batch Deduplication & Candidate Builder
        candidates = deduplicate_log_batch(pruned_logs)
        stats["deduplicated_candidates"] = len(candidates)
        logger.info(
            "Batch of %d logs collapsed into %d unique candidate patterns",
            len(pruned_logs),
            len(candidates),
        )

        # 3. Active Incident Fingerprint Lookup in Redis (L1 Exact Match)
        fps = [c.fingerprint for c in candidates]
        fp_lookup_results = await self.redis_index.lookup_fingerprints_batch(fps)

        redis_matched: List[IncidentCandidateData] = []
        novel_candidates: List[IncidentCandidateData] = []

        for candidate in candidates:
            hit_incident_id = fp_lookup_results.get(candidate.fingerprint)
            if hit_incident_id:
                redis_matched.append(candidate)
            else:
                novel_candidates.append(candidate)

        stats["redis_fingerprint_hits"] = len(redis_matched)

        # Ensure Qdrant collection exists for active candidates
        await self.vector_index.ensure_collection(vector_dim=self.embedding_provider.dimension)

        # 4. Open PostgreSQL Transaction
        async with async_session_factory() as session:
            try:
                newly_created_incidents: List[Dict[str, Any]] = []

                # 4a. Process Redis Hits: Update PostgreSQL counters (Zero Embedding Cost)
                for c in redis_matched:
                    updated = await IncidentRepository.update_by_fingerprint_hit(
                        session=session,
                        fingerprint=c.fingerprint,
                        additional_count=c.occurrence_count,
                        last_seen=c.last_seen,
                        trace_ids=c.sample_trace_ids,
                    )
                    if not updated:
                        novel_candidates.append(c)
                        stats["redis_fingerprint_hits"] -= 1

                # 4b. Process Novel Candidates
                if novel_candidates:
                    # 5. Distributed Trace Co-Occurrence Graph: Extract causal groups
                    causal_groups = self._extract_trace_connected_components(novel_candidates)
                    logger.info(
                        "Partitioned %d novel candidates into %d trace-connected causal group(s)",
                        len(novel_candidates),
                        len(causal_groups),
                    )

                    # 6. Generate Pure Error Embeddings in batch (NO service names in text)
                    all_novel_items = [c for grp in causal_groups for c in grp]
                    embedding_texts = [c.embedding_text for c in all_novel_items]
                    embeddings = await self.embedding_provider.embed_batch(embedding_texts)
                    for c, emb in zip(all_novel_items, embeddings):
                        c.embedding = emb

                    # 7. Match against Active Incidents (Qdrant & Redis trace attachment)
                    unmatched_groups: List[List[IncidentCandidateData]] = []

                    for group in causal_groups:
                        target_incident_id: Optional[uuid.UUID] = None

                        # Check if any candidate in this group shares traces with an active incident in Redis
                        for c in group:
                            for tid in c.all_trace_ids:
                                cached_inc = await self.redis_index.lookup_fingerprint(f"trace:{tid}")
                                if cached_inc:
                                    target_incident_id = uuid.UUID(cached_inc)
                                    break
                            if target_incident_id:
                                break

                        # If not matched by trace, check Qdrant semantic similarity on candidates
                        if not target_incident_id:
                            # Prioritize root cause candidate of the group to avoid generic caller match
                            root_cand = self._resolve_root_candidate(group)
                            search_order = [root_cand] + [c for c in group if c is not root_cand]
                            for c in search_order:
                                qmatch = await self.vector_index.search_nearest_active_candidate(
                                    embedding=c.embedding,
                                    score_threshold=settings.SIMILARITY_THRESHOLD,
                                )
                                if qmatch:
                                    # Validate error code compatibility if both define one
                                    matched_err = str(qmatch.get("error_code") or "").strip().upper()
                                    cand_err = str(c.error_code or "").strip().upper()
                                    if matched_err and cand_err and matched_err != cand_err:
                                        # Distinct error codes represent different defects
                                        continue

                                    target_incident_id = uuid.UUID(qmatch["incident_id"])
                                    logger.info(
                                        "Semantic match (score=%.3f) for candidate %s -> Incident %s",
                                        qmatch["score"],
                                        c.fingerprint[:8],
                                        target_incident_id,
                                    )
                                    stats["qdrant_semantic_matches"] += 1
                                    break

                        if target_incident_id:
                            # Verify target incident exists and is active in PostgreSQL (handles stale vectors/keys)
                            existing_inc = await session.get(Incident, target_incident_id)
                            if not existing_inc or existing_inc.status != "ACTIVE":
                                target_incident_id = None

                        if target_incident_id:
                            # Attach all candidates in this causal group to the existing active incident
                            redis_mappings: Dict[str, str] = {}
                            for c in group:
                                inc, cand = await IncidentRepository.attach_candidate_to_existing_incident(
                                    session=session,
                                    incident_id=target_incident_id,
                                    fingerprint=c.fingerprint,
                                    service_name=c.service_name,
                                    normalized_text=c.normalized_text,
                                    error_code=c.error_code,
                                    event_type=c.event_type,
                                    occurrence_count=c.occurrence_count,
                                    first_seen=c.first_seen,
                                    last_seen=c.last_seen,
                                    sample_trace_ids=c.sample_trace_ids,
                                    representative_log=c.representative_log,
                                    embedding_id=str(uuid.uuid4()),
                                )
                                if not inc or not cand:
                                    continue

                                redis_mappings[c.fingerprint] = str(inc.id)
                                for tid in c.sample_trace_ids:
                                    redis_mappings[f"trace:{tid}"] = str(inc.id)

                                await self.vector_index.insert_candidate_vector(
                                    candidate_id=cand.id,
                                    incident_id=inc.id,
                                    fingerprint=c.fingerprint,
                                    service_name=c.service_name,
                                    embedding=c.embedding,
                                    error_code=c.error_code,
                                    timestamp=c.last_seen.isoformat(),
                                )
                            await self.redis_index.index_fingerprints_batch(redis_mappings)
                        else:
                            unmatched_groups.append(group)

                    # 8. Novel Incident Formation for Unmatched Groups
                    if unmatched_groups:
                        # Cluster representative candidates if multiple groups exist
                        rep_candidates = [self._resolve_root_candidate(grp) for grp in unmatched_groups]
                        if len(rep_candidates) > 1:
                            clusters = self.clusterer.cluster_candidates(rep_candidates)
                            # Map clustered representatives back to their full causal groups
                            rep_to_group = {id(self._resolve_root_candidate(grp)): grp for grp in unmatched_groups}
                            final_incident_groups: List[List[IncidentCandidateData]] = []
                            for cluster_reps in clusters:
                                # Ensure distinct explicit error codes are partitioned into separate incidents
                                sub_groups_by_err: Dict[str, List[IncidentCandidateData]] = defaultdict(list)
                                for rep in cluster_reps:
                                    err_key = (rep.error_code or "").strip().upper() or f"anon_{id(rep)}"
                                    sub_groups_by_err[err_key].extend(rep_to_group.get(id(rep), [rep]))
                                final_incident_groups.extend(sub_groups_by_err.values())
                        else:
                            final_incident_groups = unmatched_groups

                        for cluster_members in final_incident_groups:
                            root_cand = self._resolve_root_candidate(cluster_members)

                            # PostgreSQL active incident deduplication fallback:
                            # If an active incident in PostgreSQL already contains any candidate fingerprint from this group,
                            # attach to it instead of creating a duplicate novel incident.
                            existing_incident: Optional[Incident] = None
                            for member in cluster_members:
                                existing_incident = await IncidentRepository.find_active_incident_by_candidate_fingerprint(
                                    session=session,
                                    fingerprint=member.fingerprint,
                                )
                                if existing_incident:
                                    break

                            if existing_incident:
                                logger.info(
                                    "Novel group matched existing active incident %s in PostgreSQL via candidate fingerprint",
                                    existing_incident.id,
                                )
                                redis_mappings: Dict[str, str] = {}
                                for c in cluster_members:
                                    inc, cand = await IncidentRepository.attach_candidate_to_existing_incident(
                                        session=session,
                                        incident_id=existing_incident.id,
                                        fingerprint=c.fingerprint,
                                        service_name=c.service_name,
                                        normalized_text=c.normalized_text,
                                        error_code=c.error_code,
                                        event_type=c.event_type,
                                        occurrence_count=c.occurrence_count,
                                        first_seen=c.first_seen,
                                        last_seen=c.last_seen,
                                        sample_trace_ids=c.sample_trace_ids,
                                        representative_log=c.representative_log,
                                        embedding_id=str(uuid.uuid4()),
                                    )
                                    if inc and cand:
                                        redis_mappings[c.fingerprint] = str(inc.id)
                                        for tid in c.sample_trace_ids:
                                            redis_mappings[f"trace:{tid}"] = str(inc.id)
                                        if c.embedding:
                                            await self.vector_index.insert_candidate_vector(
                                                candidate_id=cand.id,
                                                incident_id=inc.id,
                                                fingerprint=c.fingerprint,
                                                service_name=c.service_name,
                                                embedding=c.embedding,
                                                error_code=c.error_code,
                                                timestamp=c.last_seen.isoformat(),
                                            )
                                if redis_mappings:
                                    await self.redis_index.index_fingerprints_batch(redis_mappings)
                                continue

                            primary_service = root_cand.service_name
                            affected_services = sorted(list({m.service_name for m in cluster_members}))
                            total_occurrences = sum(m.occurrence_count for m in cluster_members)
                            earliest_seen = min(m.first_seen for m in cluster_members)
                            latest_seen = max(m.last_seen for m in cluster_members)
                            severity = self._determine_severity(cluster_members)
                            title = self._build_incident_title(primary_service, cluster_members)

                            # 9. Create Incident in PostgreSQL
                            incident = await IncidentRepository.create_incident(
                                session=session,
                                title=title,
                                primary_service=primary_service,
                                affected_services=affected_services,
                                severity=severity,
                                first_seen=earliest_seen,
                                last_seen=latest_seen,
                                total_occurrences=total_occurrences,
                                representative_log=root_cand.representative_log,
                                summary=f"Causally clustered incident for {primary_service} affecting {len(affected_services)} service(s) across {len(cluster_members)} failure pattern(s).",
                            )
                            stats["new_incidents_created"] += 1

                            redis_mappings = {}
                            qdrant_payload = []

                            for member in cluster_members:
                                cand_record = await IncidentRepository.add_candidate(
                                    session=session,
                                    incident_id=incident.id,
                                    fingerprint=member.fingerprint,
                                    service_name=member.service_name,
                                    normalized_text=member.normalized_text,
                                    error_code=member.error_code,
                                    event_type=member.event_type,
                                    occurrence_count=member.occurrence_count,
                                    first_seen=member.first_seen,
                                    last_seen=member.last_seen,
                                    sample_trace_ids=member.sample_trace_ids,
                                    representative_log=member.representative_log,
                                    embedding_id=str(uuid.uuid4()),
                                )
                                stats["new_candidates_created"] += 1
                                redis_mappings[member.fingerprint] = str(incident.id)
                                for tid in member.sample_trace_ids:
                                    redis_mappings[f"trace:{tid}"] = str(incident.id)

                                qdrant_payload.append({
                                    "candidate_id": cand_record.id,
                                    "incident_id": incident.id,
                                    "fingerprint": member.fingerprint,
                                    "service_name": member.service_name,
                                    "embedding": member.embedding,
                                    "error_code": member.error_code,
                                    "timestamp": member.last_seen.isoformat(),
                                })

                            await self.redis_index.index_fingerprints_batch(redis_mappings)
                            await self.vector_index.insert_candidate_vectors_batch(qdrant_payload)

                            newly_created_incidents.append({
                                "id": str(incident.id),
                                "primary_service": primary_service,
                                "title": title,
                                "severity": severity,
                            })

                # Commit all database writes
                await session.commit()
                logger.info("Successfully committed batch clustering transactions to PostgreSQL.")

                # Automatically trigger agent auto-investigation and notify UI via WebSocket for all newly created incidents
                for inc_info in newly_created_incidents:
                    inc_id = inc_info["id"]
                    try:
                        from backend.tasks.investigation_tasks import run_incident_investigation_task
                        run_incident_investigation_task.delay(inc_id)
                        logger.info("Automatically dispatched agent investigation for new incident %s", inc_id)
                    except Exception as dispatch_err:
                        logger.warning("Failed to auto-dispatch agent investigation for incident %s: %s", inc_id, dispatch_err)

                    try:
                        from backend.api.v1.ws import ws_manager
                        await ws_manager.broadcast({
                            "type": "incident:created",
                            "timestamp": datetime.now(timezone.utc).isoformat(),
                            "data": {
                                "incident_id": inc_id,
                                "primary_service": inc_info["primary_service"],
                                "severity": inc_info["severity"],
                                "title": inc_info["title"],
                                "message": f"New incident detected in {inc_info['primary_service']}: {inc_info['title']}",
                            },
                        })
                    except Exception as ws_err:
                        logger.debug("Silent WS broadcast failure on incident creation: %s", ws_err)

            except Exception as exc:
                await session.rollback()
                logger.error("Failed to process batch in clustering pipeline: %s", exc, exc_info=True)
                stats["status"] = "error"
                stats["error"] = str(exc)
                raise

        duration = (datetime.now(timezone.utc) - start_time).total_seconds()
        stats["duration_seconds"] = round(duration, 3)
        logger.info("Batch clustering pipeline finished in %.3fs: %s", duration, stats)
        return stats
